import Foundation

/// Canonical analytics event names emitted by the Balakun mobile SDK.
///
/// Use these constants to avoid spelling drift between client and downstream analytics routers.
public enum BalakunAnalyticsEventName {
    public static let chatSessionCreated = "chat_session_created"
    public static let chatStarted = "chat_started"
    public static let chatConversationMeaningful = "chat_conversation_meaningful"
    public static let chatWindowOpen = "chat_window_open"
    public static let chatWindowClosed = "chat_window_closed"
    public static let chatMessageSent = "chat_message_sent"
    public static let chatMessageRated = "chat_message_rated"
    public static let chatStreamError = "chat_stream_error"
    public static let chatError = "chat_error"
    public static let chatToolingStats = "chat_tooling_stats"
    public static let chatToolCalled = "chat_tool_called"
    public static let chatLogEvent = "chat_log_event"
    public static let chatNavigationCommand = "chat_navigation_command"
    public static let chatAddToBasket = "chat_add_to_basket"
    public static let chatProductLinkClick = "chat_product_link_click"
    public static let chatSubmitForm = "chat_submit_form"
    public static let chatSpeakerToggled = "chat_speaker_toggled"
    public static let chatTTSVoiceSelected = "chat_tts_voice_selected"
    public static let chatTTSPlayFailed = "chat_tts_play_failed"
    public static let chatAudioArtifactFailed = "chat_audio_artifact_failed"
}

/// Canonical metric key names used in `BalakunAnalyticsSignal.metrics`.
public enum BalakunAnalyticsKey {
    public static let origin = "origin"
    public static let path = "path"
    public static let sessionID = "session_id"
    public static let tenant = "tenant"
    public static let messageLength = "message_length"
    public static let messageID = "message_id"
    public static let rating = "rating"
    public static let responseLength = "response_length"
    public static let latencyMS = "latency_ms"
    public static let errorType = "error_type"
    public static let status = "status"
    public static let llmCalls = "llm_calls"
    public static let toolsOk = "tools_ok"
    public static let toolsFailed = "tools_failed"
    public static let toolName = "tool_name"
    public static let toolStatus = "tool_status"
    public static let modelName = "model_name"
    public static let logEventCode = "log_event_code"
    public static let logEventSeverity = "log_event_severity"
    public static let logEventSource = "log_event_source"
    public static let navAllowed = "nav_allowed"
    public static let navMode = "nav_mode"
    public static let navStage = "nav_stage"
    public static let linkSource = "link_source"
    public static let linkType = "link_type"
    public static let linkTargetHost = "link_target_host"
    public static let linkTargetPath = "link_target_path"
    public static let productPosition = "product_position"
    public static let addToBasketSource = "add_to_basket_source"
    public static let addToBasketStatus = "add_to_basket_status"
    public static let speakerEnabled = "speaker_enabled"
    public static let speakerSource = "speaker_source"
    public static let ttsEngine = "tts_engine"
    public static let ttsModel = "tts_model"
    public static let ttsVoiceID = "tts_voice_id"
    public static let ttsVoiceLang = "tts_voice_lang"
    public static let ttsMode = "tts_mode"
    public static let ttsErrorCode = "tts_error_code"
    public static let language = "language"
    public static let audioSrcScheme = "audio_src_scheme"
    public static let hasFallback = "has_fallback"
}
